# Generated by Django 4.0.1 on 2022-01-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
