# Generated by Django 4.0.1 on 2022-01-31 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_created_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created',
        ),
    ]
