# Generated by Django 4.0.1 on 2022-01-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_name_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='website.jpg', null=True, upload_to='photos/'),
        ),
    ]
