# Generated by Django 4.0.1 on 2022-01-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(default='sampleproject.jpg', upload_to='photos/%Y/%m/%d/')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null='True')),
                ('language', models.CharField(choices=[('PD', 'Python & Django'), ('ROR', 'Ruby on Rails')], max_length=50)),
            ],
        ),
    ]
