# Generated by Django 4.0.1 on 2022-01-15 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
