# Generated by Django 4.0.1 on 2022-01-15 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_project_published_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='published_at',
        ),
    ]
