# Generated by Django 4.0.1 on 2022-01-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0005_project_vote_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(default='code.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
